Fix the production build
For some reason this comment broke production, but not development.
Clicking the "Start" button gave an error:

> Error: Minified React error #152; visit
> https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=X for
> the full message or use the non-minified dev environment for full
> errors and additional helpful warnings.

From the link, the full text of the error is:

> X(...): Nothing was returned from render. This usually means a return
> statement is missing. Or, to render nothing, return null.

When I originally put the comment there I remember thinking it was
interesting that my linter/syntax checker didn't complain...